# Generated by Django 3.1.7 on 2021-03-22 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk11', models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:')),
                ('pk21', models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:')),
                ('pk31', models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:')),
                ('id_batalha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batalha_id', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_gamer_round', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL, verbose_name='What is your name?')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_gamer', to=settings.AUTH_USER_MODEL, verbose_name='Choose your opponent:')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_gamer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
