# Generated by Django 3.1.7 on 2021-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='winner',
        ),
        migrations.AddField(
            model_name='battle',
            name='pk11',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk21',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk31',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
