# Generated by Django 3.1.7 on 2021-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battling', '0002_auto_20210322_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='pk12',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk22',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pk32',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
    ]
