# Generated by Django 3.1.7 on 2021-03-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battling', '0004_auto_20210324_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='pk31',
            new_name='pk13',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='pk32',
        ),
        migrations.AddField(
            model_name='battle',
            name='pk23',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 3:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk12',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 2:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pk21',
            field=models.CharField(max_length=200, null=True, verbose_name='Pokemon 1:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='You are:'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Opponent:'),
        ),
    ]
