# Generated by Django 3.1.7 on 2021-04-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battling', '0006_auto_20210412_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='pk11',
            new_name='c_pokemon_1',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='pk12',
            new_name='c_pokemon_2',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='pk13',
            new_name='c_pokemon_3',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='player1',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='pk21',
            new_name='o_pokemon_1',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='pk22',
            new_name='o_pokemon_2',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='pk23',
            new_name='o_pokemon_3',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='player2',
            new_name='opponent',
        ),
    ]
