# Generated by Django 3.1.7 on 2021-04-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('battling', '0006_pokemonteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pokemons',
            field=models.ManyToManyField(related_name='teams', through='battling.PokemonTeam', to='pokemon.Pokemon'),
        ),
    ]
